---
title: "Open sourcing the economics of open source: A comprehensive literature review"
date: last-modified
author:
  - name: aaron-lohmann
format:
  pdf:
    fontsize: 12pt
    page-layout: full
    number-sections: true
    number-depth: 1
    link-citations: true
    keep-tex: true
    template-partials: 
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}  
                \usepackage[margin=1in]{geometry}  % Sets 1-inch margins
                \usepackage[dvipsnames]{xcolor}
        % \usepackage[top=1in, bottom=1in, left=0.8in, right=0.8in]{geometry}
bibliography: references.bib
csl: chicago-author-date.csl
abstract: |
  Open source software (OSS) is powering much of our digital infrastructure. From hosting websites, to working with databases and advancement of Machine Learning models. Recently, OSS has received increased attention from the economic discipline. Some work is motivated by the curious incentive structures, the econmic value created through OSS or the available and detailed micro-data. The goal for this project is to openly and publically craft a literature review which summarises our findings about OSS relating to economic ideas. Inspired by OSS itself, this project is open to contribution from anyone. Reward in the form of co-authorship is given according to contribution (see contribution guidelines).

  
thanks: |
  Comments, questions, and feedback are welcome and can be submitting as an issue to the repository [https://github.com/aaron-lohmann/econ-oss](https://github.com/aaron-lohmann/econ-oss/issues). Alternatively, to: \href{aaron.lohmann@uni-bielefeld.de}{aaron.lohmann@uni-bielefeld.de}.
linkcolor: NavyBlue
citecolor: NavyBlue
---

\begin{center}
\bf{Contributions welcome!}
\end{center}

Contribution guidelines: 

1. Contributions to this project must be made through a pull request to the repo [https://github.com/aaron-lohmann/econ-oss](https://github.com/aaron-lohmann/econ-oss).
2. Position in author listing will be determind by the amount of approved pull requests. Ties between the same amount of pull requests will be broken by the earliest contribution of an author.
3. Co-authorship will be granted upon two approved pull requets. One of these contributions must introduce a new citation.


\newpage


# Introduction {#sec-introduction}

Open Source Software (OSS) is key to the functioning of the modern digital infrastructure. For economists some parts of OSS propose curious questions. Why do developers contribute? Can open development outpeform closed development? On the other hand, the detailed micro data on individuals allows to study questions that are relevant to a number of knowledge intensive sectors like patenting, R \& D and the development of Work from Home. OSS provides the rare oppurunity to track for a large group of workers who works when for how long at what time. Moreover, there are questions related to global integration. How do teams form across space, how much do teams across collaborate with each other? Yet, other another aspect for OSS is the network structure. One example is to study the adoption of technology. This review tries to be comprehensive. From descriptive papers to published datasets and novel and innovati ve insights. In the end, this paper addresses two groups of readers. Those that read for knowledge and look for answers and those that read for understanding, potentially seeking to enter the field of economics of OSS. 


# Theory {#sec-theory}

Theoretical contributions which directly answer questions about OSS. 


# Datasets {#sec-datasets}

What datasets are out there to study OSS? What are benefits of one versus the other? 

@schueller2022 provide detailed data on one particular ecosystem: Rust and its associated package manager crates.io. The data covers a time period from early $2014$ all the way till September $2022$. Given the relative youth of Rust, this can be seen as representative of the full history of the language. The data covers commits, issues, pull requests, importantly dependency relationships betwenn packages. Unique in this list of datasets, the authors also provide data from other code hosting platforms outside GitHub: Gitlab, Bitbucket and the likes. This dataset is well suited for more concentrated deep micro data work given the careful construction. 


# The value of OSS {#sec-value}

@hoffmann2024value is an effort in measuring the value of OSS. The authors identify $2,000$ ($1,000$ from NPM and $1,000$ from non-NPM) key packages in the OSS infrastructure. For those they map supply side costs of creation and a demand side value based on firms and websites using these packages. Their preferred estimate for the supply side value is $4.15$ billion USD and demand side value greater than $8.8$ trillion USD.

# Geographical composition and team formation {#sec-teams}

@goldbeck2025bit concentrats on software developers in the U.S. Using the self-reported locations, develoepers are matched to 179 economic areas. Running gravity-style regressions, the author finds sizable colocation effects. However, this effect is much smaller than that of traditional inventor networks as for example in patenting. For developers with joint organizational membership or those collaborting on high quality projects, measured by stars, the colocation effect is found to be weaker.

# Team outcomes {#sec-outcomes}







# References {#sec-references}




::: {#refs}
:::


```{=tex}
\setcounter{section}{0}
\renewcommand{\thesection}{\Alph{section}}
```
```{=tex}
\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}
```
```{=tex}
\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}
```

